// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEh3_bSzFAT_kXiTC4xGFIEdQXy21Y_1I',
    appId: '1:574948100428:web:8d8e37e2149359cc5a27e9',
    messagingSenderId: '574948100428',
    projectId: 'case0-a8061',
    authDomain: 'case0-a8061.firebaseapp.com',
    storageBucket: 'case0-a8061.firebasestorage.app',
    measurementId: 'G-JXBZ4L7DX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wNoMsTNAdbbzQKJgzIMxDiehHknNZfo',
    appId: '1:574948100428:android:acd8ed256cd99d8a5a27e9',
    messagingSenderId: '574948100428',
    projectId: 'case0-a8061',
    storageBucket: 'case0-a8061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqsSNDlMPxPr_XfBgqtiGiqapgnPDl54',
    appId: '1:574948100428:ios:8f37c93ff8a2152c5a27e9',
    messagingSenderId: '574948100428',
    projectId: 'case0-a8061',
    storageBucket: 'case0-a8061.firebasestorage.app',
    iosBundleId: 'com.example.mcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqsSNDlMPxPr_XfBgqtiGiqapgnPDl54',
    appId: '1:574948100428:ios:8f37c93ff8a2152c5a27e9',
    messagingSenderId: '574948100428',
    projectId: 'case0-a8061',
    storageBucket: 'case0-a8061.firebasestorage.app',
    iosBundleId: 'com.example.mcProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEh3_bSzFAT_kXiTC4xGFIEdQXy21Y_1I',
    appId: '1:574948100428:web:85492726542172fd5a27e9',
    messagingSenderId: '574948100428',
    projectId: 'case0-a8061',
    authDomain: 'case0-a8061.firebaseapp.com',
    storageBucket: 'case0-a8061.firebasestorage.app',
    measurementId: 'G-FKK96M3B4V',
  );
}
